services:
- type: web
  name: next-js
  runtime: node
  plan: starter
  buildCommand: npm i; npm run build
  startCommand: npm run build
  autoDeploy: false
  envVars:
  - key: NODE_ENV
    value: production
